services:
  MaricTrading\Parchemin:
      public: true

  MaricTrading\Parchemin\Repository\PageRepository:
    public: true
    arguments:
      $registry: '@doctrine'

  MaricTrading\Parchemin\Controller\PageController:
    public: true
    arguments:
      $pageRepository: '@MaricTrading\Parchemin\Repository\PageRepository'
      $twig: '@twig'
