services:
  MaricTrading\Parchemin:
      public: true

  MaricTrading\Parchemin\Repository\PageRepository:
    public: true
    arguments:
      $entityManager: '@doctrine.orm.default_entity_manager'

  MaricTrading\Parchemin\Controller\PageController:
    public: true
    calls:
    -   setContainer: [ '@service_container' ]
    tags: ['controller.service_arguments', 'container.service_subscriber']
    arguments:
      $pageRepository: '@MaricTrading\Parchemin\Repository\PageRepository'
      $twig: '@twig'
      $editRole: '%maric_trading.parchemin.edit_role%'
      $allowRaw : '%maric_trading.parchemin.allow_raw%'

  MaricTrading\Parchemin\Controller\SitemapController:
    public: true
    tags: ['controller.service_arguments', 'container.service_subscriber']
    calls:
      -   setContainer: [ '@service_container' ]
    arguments:
      $pageRepository: '@MaricTrading\Parchemin\Repository\PageRepository'
      $additionalSitemapRoutes: '%maric_trading.parchemin.additional_sitemap_routes%'

